import type { DrillLine } from '@/lib/drills/types'

function line(
  id: string,
  name: string,
  summary: string,
  eco: string | undefined,
  pairs: Array<[string, string]>,
): DrillLine {
  return {
    id,
    name,
    summary,
    eco,
    moves: pairs.map(([san, hint]) => ({ san, hint })),
  }
}

/** Italian Opening drill pack — original names & hints (public theory stems). */
export const ITALIAN_LINES: DrillLine[] = [
  line(
    'rook-bait',
    'Rook Bait',
    'Greco trap with Ba3 — greed on a1 loses the queen.',
    'C54',
    [
      ['e4', 'Claim the center and free the bishop.'],
      ['e5', 'Black mirrors — now develop with tempo.'],
      ['Nf3', 'Attack e5 and prepare the Italian bishop.'],
      ['Nc6', 'They defend e5 — time for Bc4.'],
      ['Bc4', 'Aim at f7, the softest square.'],
      ['Bc5', 'Giuoco Piano. Build the big center with c3.'],
      ['c3', 'Prepare d4 — classical Italian plan.'],
      ['Nf6', 'They hit e4. Push the center anyway.'],
      ['d4', 'Open the middle before they castle.'],
      ['exd4', 'They take — recapture and keep both center pawns.'],
      ['cxd4', 'Ideal duo on d4 and e4.'],
      ['Bb4+', 'Check. Offer the gambit with Nc3.'],
      ['Nc3', 'Sacrifice e4 for development.'],
      ['Nxe4', 'They snatch the pawn — castle into the attack.'],
      ['O-O', 'King safe; every piece wakes up.'],
      ['Nxc3', 'They take on c3 — open the b-file.'],
      ['bxc3', 'Recapture toward the center.'],
      ['Bxc3', 'Second pawn. Now Ba3 stops castling forever.'],
      ['Ba3', 'Pin ideas and cut O-O. Wait for greed.'],
      ['Bxa1', 'They grab the rook — punish immediately.'],
      ['Re1+', 'Check forces the knight into the pin.'],
      ['Ne7', 'Only move — now harvest the queen.'],
      ['Bxe7', 'Clear the pin with tempo.'],
      ['Qxe7', 'Forced — the rook finishes it.'],
      ['Rxe7+', 'Queen gone; king stuck in the center.'],
      ['Kxe7', 'Recapture — collect the hanging rook.'],
      ['Qxa1', 'Material and development. Drill complete.'],
    ],
  ),
  line(
    'bishop-retreat',
    'Bishop Retreat Trap',
    'Passive …Bb6 lets the center roll over the knight.',
    'C54',
    [
      ['e4', 'Same Italian start — center first.'],
      ['e5', 'Symmetry — develop Nf3.'],
      ['Nf3', 'Pressure e5.'],
      ['Nc6', 'Defend — Bc4 next.'],
      ['Bc4', 'Eye f7.'],
      ['Bc5', 'Piano. Support d4 with c3.'],
      ['c3', 'Ready the pawn break.'],
      ['Nf6', 'Hit e4 — still push d4.'],
      ['d4', 'Open up.'],
      ['exd4', 'Take back with the c-pawn.'],
      ['cxd4', 'Center secured.'],
      ['Bb6', 'Retreat instead of the check — punish with e5.'],
      ['e5', 'Kick the knight off f6.'],
      ['Ng4', 'Awkward jump — chase it with h3.'],
      ['h3', 'Ask the knight where it lives.'],
      ['Nh6', 'Rim knight. Expand with d5.'],
      ['d5', 'Gain space and hit c6.'],
      ['Na5', 'They attack the bishop — pin with Bg5.'],
      ['Bg5', 'Bind the kingside.'],
      ['f6', 'They break the pin — rip open with exf6.'],
      ['exf6', 'Structure shattered. Good enough for the drill.'],
    ],
  ),
  line(
    'pin-and-lift',
    'Pin and Lift',
    'Aitken idea: Ba3, then Rc1–Qa4 harvests the bishop.',
    'C54',
    [
      ['e4', 'Center.'],
      ['e5', 'Mirror.'],
      ['Nf3', 'Develop.'],
      ['Nc6', 'Defend e5.'],
      ['Bc4', 'Italian bishop.'],
      ['Bc5', 'Piano.'],
      ['c3', 'Prep d4.'],
      ['Nf6', 'Counter on e4.'],
      ['d4', 'Break.'],
      ['exd4', 'Recapture.'],
      ['cxd4', 'Duo.'],
      ['Bb4+', 'Check — gambit Nc3.'],
      ['Nc3', 'Offer e4.'],
      ['Nxe4', 'Take — castle.'],
      ['O-O', 'Safety.'],
      ['Nxc3', 'Open b.'],
      ['bxc3', 'Recapture.'],
      ['Bxc3', 'Greedy bishop — Ba3.'],
      ['Ba3', 'No castling.'],
      ['d6', 'They try to free — lift the rook.'],
      ['Rc1', 'Pin along the c-file.'],
      ['Ba5', 'Slide away — hunt with the queen.'],
      ['Qa4', 'Double attack themes.'],
      ['O-O', 'They finally castle — clamp the center.'],
      ['d5', 'Kick the knight.'],
      ['Ne5', 'Central hop — trade and win the bishop.'],
      ['Nxe5', 'Clear c6 ideas.'],
      ['dxe5', 'Recapture — take on a5.'],
      ['Qxa5', 'Bishop collected. Line done.'],
    ],
  ),
  line(
    'skewer-queue',
    'Skewer Queue',
    'After Ba3 d6 Rc1, …Bb4 walks into Qe1–Qxb4.',
    'C54',
    [
      ['e4', 'Center.'],
      ['e5', 'Mirror.'],
      ['Nf3', 'Develop.'],
      ['Nc6', 'Defend.'],
      ['Bc4', 'Italian.'],
      ['Bc5', 'Piano.'],
      ['c3', 'Prep.'],
      ['Nf6', 'Hit e4.'],
      ['d4', 'Break.'],
      ['exd4', 'Take.'],
      ['cxd4', 'Recapture.'],
      ['Bb4+', 'Check.'],
      ['Nc3', 'Gambit.'],
      ['Nxe4', 'Pawn.'],
      ['O-O', 'Castle.'],
      ['Nxc3', 'Trade.'],
      ['bxc3', 'Open.'],
      ['Bxc3', 'Greed.'],
      ['Ba3', 'Cut castling.'],
      ['d6', 'Breathing room.'],
      ['Rc1', 'File pressure.'],
      ['Bb4', 'They interpose — remove the defender.'],
      ['Bxb4', 'Trade bishops.'],
      ['Nxb4', 'Knight takes — skewer the king and knight.'],
      ['Qe1+', 'Check discovers the win.'],
      ['Qe7', 'Block — take the knight.'],
      ['Qxb4', 'Extra piece. Done.'],
    ],
  ),
  line(
    'quiet-castle',
    'Quiet Castle',
    '…h6 instead of …Nf6 — stay calm and castle into comfort.',
    'C53',
    [
      ['e4', 'Center.'],
      ['e5', 'Mirror.'],
      ['Nf3', 'Develop.'],
      ['Nc6', 'Defend.'],
      ['Bc4', 'Italian.'],
      ['Bc5', 'Piano.'],
      ['c3', 'Prep d4.'],
      ['h6', 'Slow move — still break in the center.'],
      ['d4', 'Open before they catch up.'],
      ['exd4', 'Take.'],
      ['cxd4', 'Duo.'],
      ['Bb4+', 'Check — develop Nc3.'],
      ['Nc3', 'Natural block.'],
      ['d6', 'Solid — castle and enjoy the lead.'],
      ['O-O', 'King home. Drill complete.'],
    ],
  ),
  line(
    'overload-a1',
    'Overload on a1',
    '…h6 then the Greco rook grab — Bxf7+ wrecks the king.',
    'C53',
    [
      ['e4', 'Center.'],
      ['e5', 'Mirror.'],
      ['Nf3', 'Knight out.'],
      ['Nc6', 'Defend.'],
      ['Bc4', 'Bishop.'],
      ['Bc5', 'Piano.'],
      ['c3', 'Prep.'],
      ['h6', 'Slow — still d4.'],
      ['d4', 'Break.'],
      ['exd4', 'Take.'],
      ['cxd4', 'Recapture.'],
      ['Bb4+', 'Check.'],
      ['Nc3', 'Block.'],
      ['Nf6', 'Finally develop — push e5.'],
      ['e5', 'Kick the knight.'],
      ['Ne4', 'Central outpost — castle and ignore.'],
      ['O-O', 'Safety first.'],
      ['Nxc3', 'They take — open the queen path.'],
      ['bxc3', 'Recapture.'],
      ['Bxc3', 'Greedy — queen hits f7 and a1 themes.'],
      ['Qb3', 'Double attack on f7 / b7 ideas.'],
      ['Bxa1', 'Rook bait accepted — smash f7.'],
      ['Bxf7+', 'King exposed.'],
      ['Kf8', 'Only — discover with Ba3+.'],
      ['Ba3+', 'Empty check lane.'],
      ['d6', 'Block — rip the center.'],
      ['exd6', 'Open files.'],
      ['cxd6', 'Take — reload the bishop.'],
      ['Bg6', 'Bind the king.'],
      ['Qf6', 'Defend — trade into the pin.'],
      ['Bxd6+', 'Check.'],
      ['Ne7', 'Interpose — lift the rook.'],
      ['Re1', 'Pin and pressure. Line done.'],
    ],
  ),
  line(
    'knight-kick-mate',
    'Knight Kick Mate',
    'Møller 9.d5 — …Ne5 hangs mate after Qxg7.',
    'C54',
    [
      ['e4', 'Center.'],
      ['e5', 'Mirror.'],
      ['Nf3', 'Develop.'],
      ['Nc6', 'Defend.'],
      ['Bc4', 'Italian.'],
      ['Bc5', 'Piano.'],
      ['c3', 'Prep.'],
      ['Nf6', 'Hit e4.'],
      ['d4', 'Break.'],
      ['exd4', 'Take.'],
      ['cxd4', 'Duo.'],
      ['Bb4+', 'Check.'],
      ['Nc3', 'Gambit.'],
      ['Nxe4', 'Pawn.'],
      ['O-O', 'Castle.'],
      ['Bxc3', 'Best capture — now Møller.'],
      ['d5', 'Kick the knight; open e.'],
      ['Ne5', 'Wrong square — open the queen.'],
      ['bxc3', 'Recapture.'],
      ['Nxc4', 'They take the bishop — queen centralizes.'],
      ['Qd4', 'Hit both knights and g7.'],
      ['Ncd6', 'Save one — crash through on g7.'],
      ['Qxg7', 'King stripped.'],
      ['Qf6', 'Trade queens — keep checking.'],
      ['Qxf6', 'Clear.'],
      ['Nxf6', 'Recapture — rook check.'],
      ['Re1+', 'King walk.'],
      ['Kf8', 'Corner — bishop check.'],
      ['Bh6+', 'Shelter gone.'],
      ['Kg8', 'Only — rook lift.'],
      ['Re5', 'Mate net forming.'],
      ['Nde4', 'Guard g5 — bring the knight.'],
      ['Nd2', 'Challenge.'],
      ['d6', 'Breath — trade and mate.'],
      ['Nxe4', 'Clear.'],
      ['Nxe4', 'Recapture — back-rank mate.'],
      ['Re8#', 'Mate. Done.'],
    ],
  ),
  line(
    'rook-sweep',
    'Rook Sweep',
    'Same Møller branch — squeeze both rooks after Qxg7.',
    'C54',
    [
      ['e4', 'Center.'],
      ['e5', 'Mirror.'],
      ['Nf3', 'Develop.'],
      ['Nc6', 'Defend.'],
      ['Bc4', 'Italian.'],
      ['Bc5', 'Piano.'],
      ['c3', 'Prep.'],
      ['Nf6', 'Hit e4.'],
      ['d4', 'Break.'],
      ['exd4', 'Take.'],
      ['cxd4', 'Duo.'],
      ['Bb4+', 'Check.'],
      ['Nc3', 'Gambit.'],
      ['Nxe4', 'Pawn.'],
      ['O-O', 'Castle.'],
      ['Bxc3', 'Take.'],
      ['d5', 'Møller.'],
      ['Ne5', 'Sideline.'],
      ['bxc3', 'Recapture.'],
      ['Nxc4', 'Bishop.'],
      ['Qd4', 'Centralize.'],
      ['Ncd6', 'Save.'],
      ['Qxg7', 'Crash.'],
      ['Qf6', 'Trade.'],
      ['Qxf6', 'Clear.'],
      ['Nxf6', 'Take.'],
      ['Re1+', 'Check.'],
      ['Kf8', 'Walk.'],
      ['Bh6+', 'Shelter.'],
      ['Kg8', 'Only.'],
      ['Re5', 'Lift.'],
      ['Nfe4', 'Other knight — double the rooks.'],
      ['Re1', 'Pin ideas.'],
      ['f6', 'Kick — invade the 7th.'],
      ['Re7', 'Seventh heaven.'],
      ['Nf5', 'Harass — check again.'],
      ['Re8+', 'King out.'],
      ['Kf7', 'Walk — take the rook.'],
      ['Rxh8', 'Material.'],
      ['Nxh6', 'Take bishop — clean the e4 knight.'],
      ['Rxe4', 'Calm end. Done.'],
    ],
  ),
  line(
    'bishop-hold',
    'Bishop Hold',
    'Main Møller — …Bf6, regain the piece, keep the initiative.',
    'C54',
    [
      ['e4', 'Center.'],
      ['e5', 'Mirror.'],
      ['Nf3', 'Develop.'],
      ['Nc6', 'Defend.'],
      ['Bc4', 'Italian.'],
      ['Bc5', 'Piano.'],
      ['c3', 'Prep.'],
      ['Nf6', 'Hit e4.'],
      ['d4', 'Break.'],
      ['exd4', 'Take.'],
      ['cxd4', 'Duo.'],
      ['Bb4+', 'Check.'],
      ['Nc3', 'Gambit.'],
      ['Nxe4', 'Pawn.'],
      ['O-O', 'Castle.'],
      ['Bxc3', 'Correct.'],
      ['d5', 'Møller kick.'],
      ['Bf6', 'Best — hold the piece later.'],
      ['Re1', 'Pin the e4 knight.'],
      ['Ne7', 'Support — take back on e4.'],
      ['Rxe4', 'Material even-ish; keep attacking.'],
      ['d6', 'Solidify — pin with Bg5.'],
      ['Bg5', 'Trade into an open king hunt.'],
      ['Bxg5', 'Take.'],
      ['Nxg5', 'Knight in. Line pause point — initiative secured.'],
    ],
  ),
  line(
    'storm-f7',
    'Storm on f7',
    'After …h6 Bb5+ c6, Nxf7 blows the shelter.',
    'C54',
    [
      ['e4', 'Center.'],
      ['e5', 'Mirror.'],
      ['Nf3', 'Develop.'],
      ['Nc6', 'Defend.'],
      ['Bc4', 'Italian.'],
      ['Bc5', 'Piano.'],
      ['c3', 'Prep.'],
      ['Nf6', 'Hit e4.'],
      ['d4', 'Break.'],
      ['exd4', 'Take.'],
      ['cxd4', 'Duo.'],
      ['Bb4+', 'Check.'],
      ['Nc3', 'Gambit.'],
      ['Nxe4', 'Pawn.'],
      ['O-O', 'Castle.'],
      ['Bxc3', 'Take.'],
      ['d5', 'Møller.'],
      ['Bf6', 'Hold.'],
      ['Re1', 'Pin.'],
      ['Ne7', 'Support.'],
      ['Rxe4', 'Regain.'],
      ['d6', 'Solid.'],
      ['Bg5', 'Pin.'],
      ['Bxg5', 'Trade.'],
      ['Nxg5', 'In.'],
      ['h6', 'Kick — check on b5.'],
      ['Bb5+', 'Disturb the king.'],
      ['c6', 'Block — sacrifice on f7.'],
      ['Nxf7', 'King drawn out.'],
      ['Kxf7', 'Take — queen check.'],
      ['Qf3+', 'King hunt.'],
      ['Kg8', 'Back — double rooks.'],
      ['Rae1', 'All hands.'],
      ['cxb5', 'They grab — crash on e7.'],
      ['Rxe7', 'Collapse. Done.'],
    ],
  ),
  line(
    'soft-mate-net',
    'Soft Mate Net',
    'Suffocation themes — queen lands on h8.',
    'C54',
    [
      ['e4', 'Center.'],
      ['e5', 'Mirror.'],
      ['Nf3', 'Develop.'],
      ['Nc6', 'Defend.'],
      ['Bc4', 'Italian.'],
      ['Bc5', 'Piano.'],
      ['c3', 'Prep.'],
      ['Nf6', 'Hit e4.'],
      ['d4', 'Break.'],
      ['exd4', 'Take.'],
      ['cxd4', 'Duo.'],
      ['Bb4+', 'Check.'],
      ['Nc3', 'Gambit.'],
      ['Nxe4', 'Pawn.'],
      ['O-O', 'Castle.'],
      ['Bxc3', 'Take.'],
      ['d5', 'Møller.'],
      ['Bf6', 'Hold.'],
      ['Re1', 'Pin.'],
      ['Ne7', 'Support.'],
      ['Rxe4', 'Regain.'],
      ['d6', 'Solid.'],
      ['Bg5', 'Pin.'],
      ['Bxg5', 'Trade.'],
      ['Nxg5', 'In.'],
      ['h6', 'Kick.'],
      ['Bb5+', 'Check — king steps wrong.'],
      ['Kf8', 'No castle — queen joins.'],
      ['Qh5', 'Threaten mate ideas.'],
      ['g6', 'Kick — slide to f3.'],
      ['Qf3', 'Keep pressure.'],
      ['hxg5', 'They take — invade f6.'],
      ['Qf6', 'Bind.'],
      ['Rh4', 'Desperate lift — take it.'],
      ['Rxh4', 'Clear.'],
      ['gxh4', 'Recapture — rook again.'],
      ['Re1', 'Fresh battery.'],
      ['Bd7', 'Develop — smash e7.'],
      ['Rxe7', 'Clear the queen.'],
      ['Qxe7', 'Forced — mate.'],
      ['Qh8#', 'Suffocation mate. Done.'],
    ],
  ),
  line(
    'bazooka-file',
    'Bazooka File',
    '…Bd7 meets Qe2 and doubled rooks on the e-file.',
    'C54',
    [
      ['e4', 'Center.'],
      ['e5', 'Mirror.'],
      ['Nf3', 'Develop.'],
      ['Nc6', 'Defend.'],
      ['Bc4', 'Italian.'],
      ['Bc5', 'Piano.'],
      ['c3', 'Prep.'],
      ['Nf6', 'Hit e4.'],
      ['d4', 'Break.'],
      ['exd4', 'Take.'],
      ['cxd4', 'Duo.'],
      ['Bb4+', 'Check.'],
      ['Nc3', 'Gambit.'],
      ['Nxe4', 'Pawn.'],
      ['O-O', 'Castle.'],
      ['Bxc3', 'Take.'],
      ['d5', 'Møller.'],
      ['Bf6', 'Hold.'],
      ['Re1', 'Pin.'],
      ['Ne7', 'Support.'],
      ['Rxe4', 'Regain.'],
      ['d6', 'Solid.'],
      ['Bg5', 'Pin.'],
      ['Bxg5', 'Trade.'],
      ['Nxg5', 'In.'],
      ['h6', 'Kick.'],
      ['Bb5+', 'Check.'],
      ['Bd7', 'Interpose — queen aligns.'],
      ['Qe2', 'Battery on e.'],
      ['hxg5', 'Take — double rooks.'],
      ['Re1', 'All in.'],
      ['O-O', 'Castle late — crash e7.'],
      ['Rxe7', 'Clear.'],
      ['Bxb5', 'Trade — queen recaptures.'],
      ['Qxb5', 'Extra exchange pressure. Done.'],
    ],
  ),
  line(
    'king-hunt-draw',
    'King Hunt Draw',
    'Famous Nxh7 idea — know the attacking pattern.',
    'C54',
    [
      ['e4', 'Center.'],
      ['e5', 'Mirror.'],
      ['Nf3', 'Develop.'],
      ['Nc6', 'Defend.'],
      ['Bc4', 'Italian.'],
      ['Bc5', 'Piano.'],
      ['c3', 'Prep.'],
      ['Nf6', 'Hit e4.'],
      ['d4', 'Break.'],
      ['exd4', 'Take.'],
      ['cxd4', 'Duo.'],
      ['Bb4+', 'Check.'],
      ['Nc3', 'Gambit.'],
      ['Nxe4', 'Pawn.'],
      ['O-O', 'Castle.'],
      ['Bxc3', 'Take.'],
      ['d5', 'Møller.'],
      ['Bf6', 'Hold.'],
      ['Re1', 'Pin.'],
      ['Ne7', 'Support.'],
      ['Rxe4', 'Regain.'],
      ['d6', 'Solid.'],
      ['Bg5', 'Pin.'],
      ['Bxg5', 'Trade.'],
      ['Nxg5', 'In.'],
      ['O-O', 'They castle into the sac.'],
      ['Nxh7', 'Classic Greek gift mood.'],
      ['Kxh7', 'Take — queen check.'],
      ['Qh5+', 'King hunt.'],
      ['Kg8', 'Back — rook lift.'],
      ['Rh4', 'Threaten mate. Pattern locked.'],
    ],
  ),
  line(
    'tempo-recapture',
    'Tempo Recapture',
    '…Ne5 then …O-O — queen takes on c4 with tempo.',
    'C54',
    [
      ['e4', 'Center.'],
      ['e5', 'Mirror.'],
      ['Nf3', 'Develop.'],
      ['Nc6', 'Defend.'],
      ['Bc4', 'Italian.'],
      ['Bc5', 'Piano.'],
      ['c3', 'Prep.'],
      ['Nf6', 'Hit e4.'],
      ['d4', 'Break.'],
      ['exd4', 'Take.'],
      ['cxd4', 'Duo.'],
      ['Bb4+', 'Check.'],
      ['Nc3', 'Gambit.'],
      ['Nxe4', 'Pawn.'],
      ['O-O', 'Castle.'],
      ['Bxc3', 'Take.'],
      ['d5', 'Møller.'],
      ['Ne5', 'Sideline.'],
      ['bxc3', 'Recapture.'],
      ['Nxc4', 'Bishop.'],
      ['Qd4', 'Centralize.'],
      ['O-O', 'They castle — take the knight.'],
      ['Qxc4', 'Tempo on the remaining knight.'],
      ['Nd6', 'Kick — queen slides.'],
      ['Qb3', 'Safe square. Done.'],
    ],
  ),
  line(
    'fork-check',
    'Fork Check',
    'Two Knights greed …Nxe4 meets Qd5.',
    'C56',
    [
      ['e4', 'Center.'],
      ['e5', 'Mirror.'],
      ['Nf3', 'Develop.'],
      ['Nc6', 'Defend.'],
      ['Bc4', 'Italian.'],
      ['Nf6', 'Two Knights — strike with d4.'],
      ['d4', 'Open immediately.'],
      ['Nxe4', 'Greedy — push past.'],
      ['dxe5', 'Open lines to f7.'],
      ['Bc5', 'They eye f2 — fork with the queen.'],
      ['Qd5', 'Hits e4 and f7.'],
      ['Bxf2+', 'Spite check — step aside.'],
      ['Kf1', 'King walks; queen still wins.'],
      ['O-O', 'Castle — take the knight.'],
      ['Qxe4', 'Extra piece. Done.'],
    ],
  ),
  line(
    'central-clamp',
    'Central Clamp',
    '…d6 vs 4.d4 — grab space with d5.',
    'C55',
    [
      ['e4', 'Center.'],
      ['e5', 'Mirror.'],
      ['Nf3', 'Develop.'],
      ['Nc6', 'Defend.'],
      ['Bc4', 'Italian.'],
      ['Nf6', 'Two Knights.'],
      ['d4', 'Open.'],
      ['d6', 'Passive hold — clamp with d5.'],
      ['d5', 'Space and kick. Done.'],
    ],
  ),
  line(
    'loose-queen',
    'Loose Queen',
    'Anderssen Attack — …Qd8 walks into Rxe4+ and a free exchange.',
    'C56',
    [
      ['e4', 'Center.'],
      ['e5', 'Mirror.'],
      ['Nf3', 'Develop.'],
      ['Nc6', 'Defend.'],
      ['Bc4', 'Italian.'],
      ['Nf6', 'Two Knights.'],
      ['d4', 'Open.'],
      ['exd4', 'Take.'],
      ['O-O', 'Gambit style.'],
      ['Nxe4', 'Pawn — pin with Re1.'],
      ['Re1', 'Pressure e4.'],
      ['d5', 'Only break — sacrifice the bishop.'],
      ['Bxd5', 'Key resource.'],
      ['Qxd5', 'Forced — fork with Nc3.'],
      ['Nc3', 'Queen and knight.'],
      ['Qd8', 'Retreat — take with check.'],
      ['Rxe4+', 'Check.'],
      ['Be7', 'Block — grab d4.'],
      ['Nxd4', 'Centralize.'],
      ['O-O', 'Castle — trade on c6.'],
      ['Nxc6', 'Damage.'],
      ['Qxd1+', 'Trade queens.'],
      ['Nxd1', 'Recapture.'],
      ['bxc6', 'Structure — take on e7.'],
      ['Rxe7', 'Exchange up. Done.'],
    ],
  ),
  line(
    'pin-royal',
    'Pin Royal',
    'Anderssen with …Qa5 — Neg5 and the e-file pin.',
    'C56',
    [
      ['e4', 'Center.'],
      ['e5', 'Mirror.'],
      ['Nf3', 'Develop.'],
      ['Nc6', 'Defend.'],
      ['Bc4', 'Italian.'],
      ['Nf6', 'Two Knights.'],
      ['d4', 'Open.'],
      ['exd4', 'Take.'],
      ['O-O', 'Castle.'],
      ['Nxe4', 'Pawn.'],
      ['Re1', 'Pin.'],
      ['d5', 'Break.'],
      ['Bxd5', 'Sac.'],
      ['Qxd5', 'Take.'],
      ['Nc3', 'Fork.'],
      ['Qa5', 'Active queen — take e4.'],
      ['Nxe4', 'Clear.'],
      ['Be6', 'Develop — jump Neg5.'],
      ['Neg5', 'Pressure e6 / f7.'],
      ['O-O-O', 'Long castle — take on e6.'],
      ['Nxe6', 'Damage.'],
      ['fxe6', 'Recapture — rook in.'],
      ['Rxe6', 'Pin ideas.'],
      ['Bd6', 'Block — pin with Bg5.'],
      ['Bg5', 'Bind.'],
      ['Rde8', 'Challenge — align the queen.'],
      ['Qe2', 'Battery. Done.'],
    ],
  ),
  line(
    'structure-crunch',
    'Structure Crunch',
    'Trade queens after …Qd8 and sit on the c-file.',
    'C56',
    [
      ['e4', 'Center.'],
      ['e5', 'Mirror.'],
      ['Nf3', 'Develop.'],
      ['Nc6', 'Defend.'],
      ['Bc4', 'Italian.'],
      ['Nf6', 'Two Knights.'],
      ['d4', 'Open.'],
      ['exd4', 'Take.'],
      ['O-O', 'Castle.'],
      ['Nxe4', 'Pawn.'],
      ['Re1', 'Pin.'],
      ['d5', 'Break.'],
      ['Bxd5', 'Sac.'],
      ['Qxd5', 'Take.'],
      ['Nc3', 'Fork.'],
      ['Qd8', 'Back.'],
      ['Rxe4+', 'Check.'],
      ['Be7', 'Block.'],
      ['Nxd4', 'Center.'],
      ['O-O', 'Castle.'],
      ['Nxc6', 'Trade.'],
      ['bxc6', 'Damage.'],
      ['Qxd8', 'Queens off.'],
      ['Bxd8', 'Recapture — rook to c4.'],
      ['Rc4', 'Sit on the weak pawns. Done.'],
    ],
  ),
  line(
    'quiet-queen',
    'Quiet Queen',
    '…Qh5 line — trade on d6 and clamp with c3.',
    'C56',
    [
      ['e4', 'Center.'],
      ['e5', 'Mirror.'],
      ['Nf3', 'Develop.'],
      ['Nc6', 'Defend.'],
      ['Bc4', 'Italian.'],
      ['Nf6', 'Two Knights.'],
      ['d4', 'Open.'],
      ['exd4', 'Take.'],
      ['O-O', 'Castle.'],
      ['Nxe4', 'Pawn.'],
      ['Re1', 'Pin.'],
      ['d5', 'Break.'],
      ['Bxd5', 'Sac.'],
      ['Qxd5', 'Take.'],
      ['Nc3', 'Fork.'],
      ['Qh5', 'Active — take e4.'],
      ['Nxe4', 'Clear.'],
      ['Be6', 'Develop — pin Bg5.'],
      ['Bg5', 'Bind.'],
      ['Bd6', 'Block — trade on d6.'],
      ['Nxd6+', 'Damage structure.'],
      ['cxd6', 'Recapture — bishop to f4.'],
      ['Bf4', 'Hit d6.'],
      ['Qd5', 'Centralize — clamp with c3.'],
      ['c3', 'Solid. Done.'],
    ],
  ),
  line(
    'long-castle-battery',
    'Long Castle Battery',
    'Philidor Antoshin — Bf4, Qd2, O-O-O.',
    'C41',
    [
      ['e4', 'Center.'],
      ['e5', 'Mirror.'],
      ['Nf3', 'Develop.'],
      ['d6', 'Philidor — open with d4.'],
      ['d4', 'Challenge.'],
      ['exd4', 'Take.'],
      ['Nxd4', 'Recapture.'],
      ['Nf6', 'Develop.'],
      ['Nc3', 'Natural.'],
      ['Be7', 'Antoshin — bishop out before castling.'],
      ['Bf4', 'Aim at the kingside.'],
      ['O-O', 'They castle — queen connects.'],
      ['Qd2', 'Battery toward h6 ideas.'],
      ['a6', 'Slow — castle long.'],
      ['O-O-O', 'Opposite castles. Done.'],
    ],
  ),
  line(
    'trade-and-castle',
    'Trade and Castle',
    'Philidor with …Nc6 — trade, then castle queenside.',
    'C41',
    [
      ['e4', 'Center.'],
      ['e5', 'Mirror.'],
      ['Nf3', 'Develop.'],
      ['d6', 'Philidor.'],
      ['d4', 'Break.'],
      ['Nc6', 'Odd — pin with Bb5.'],
      ['Bb5', 'Spanish flavor.'],
      ['Bd7', 'Break pin — develop Nc3.'],
      ['Nc3', 'Pressure.'],
      ['exd4', 'Take.'],
      ['Nxd4', 'Recapture.'],
      ['Nxd4', 'Trade.'],
      ['Bxd7+', 'Clear.'],
      ['Qxd7', 'Recapture.'],
      ['Qxd4', 'Central queen.'],
      ['Nf6', 'Develop — pin Bg5.'],
      ['Bg5', 'Bind.'],
      ['Be7', 'Break — castle long.'],
      ['O-O-O', 'Ready to attack. Done.'],
    ],
  ),
  line(
    'pinpoint-attack',
    'Pinpoint Attack',
    'Philidor …Nc6 without …Bd7 — queen takes d4 early.',
    'C41',
    [
      ['e4', 'Center.'],
      ['e5', 'Mirror.'],
      ['Nf3', 'Develop.'],
      ['d6', 'Philidor.'],
      ['d4', 'Break.'],
      ['Nc6', 'Develop — pin Bb5.'],
      ['Bb5', 'Pressure.'],
      ['exd4', 'Open — take with the queen.'],
      ['Qxd4', 'Centralize.'],
      ['Bd7', 'Break — trade on c6.'],
      ['Bxc6', 'Damage.'],
      ['Bxc6', 'Recapture.'],
      ['Nc3', 'Develop.'],
      ['Nf6', 'Out — pin Bg5.'],
      ['Bg5', 'Bind.'],
      ['Be7', 'Break — castle long.'],
      ['O-O-O', 'Attack ready. Done.'],
    ],
  ),
]

export function getItalianLine(id: string): DrillLine | undefined {
  return ITALIAN_LINES.find((l) => l.id === id)
}
