[package]
name = "explorer-build"
version = "0.1.0"
edition = "2021"

[dependencies]
crossbeam-channel = "0.5"
rusqlite = { version = "0.32", features = ["bundled"] }
rustc-hash = "2"
shakmaty = "0.29"

[profile.release]
lto = "thin"
codegen-units = 1
panic = "abort"

[profile.fast]
inherits = "release"
lto = false
codegen-units = 16
